version: "3"
services:
  flaskapp:
    container_name: calc_filipelopesmedbr_flaskapp
    build:
      context: ./flaskapp
      dockerfile: Dockerfile
    volumes:
      - ./flaskapp:/app
    ports:
      - "${FLASKAPP_PORT}:5000"
  nginx:
    container_name: calc_filipelopesmedbr_nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - flaskapp
