version: "3"
services:
  app:
    container_name: filipelopesmedbr_calc_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8005:8000
  nginx:
    container_name: filipelopesmedbr_calc_nginx
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${APP_PORT}:80
    depends_on:
      - app